version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: webhook_postgres
    restart: always
    environment:
      POSTGRES_USER: tendresse
      POSTGRES_PASSWORD: psw123
      POSTGRES_DB: webhook_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
